<a href="https://colab.research.google.com/github/spshreya/pytorch_practice/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals FreeCodeCamp mrdbrouke

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


#Introduction to Tensors

##Creating Tensors

In [3]:
#scalar
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.ndim  #scalar has no dimensions

0

In [6]:
scalar.item()  #tensor back as python int

7

In [7]:
#vector
vector = torch.tensor((1,7))
vector

tensor([1, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
  #Matrix

  MATRIX = torch.tensor([[7,8],
                         [9,10]])
  MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape   #we have 1 -3*3 matrix

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

They are important as many NNs learn is that when they start, it is with random numbers and then adjust the numbers to a better representation of numbers



start with random numbers -> look at data -> update random numbers -> look at data -> update

In [22]:
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[8.4014e-01, 4.5818e-01, 9.2637e-01, 9.3633e-01, 4.4082e-01,
          6.1227e-01, 2.0745e-01, 6.4948e-01, 5.3920e-01, 4.8064e-01],
         [7.3105e-01, 3.4198e-01, 8.3770e-01, 5.0405e-01, 9.5320e-01,
          6.2645e-02, 4.8919e-01, 3.4341e-01, 7.5984e-01, 3.7868e-01],
         [4.9910e-01, 4.8046e-01, 5.1814e-01, 1.8141e-02, 6.3722e-01,
          3.4580e-01, 6.8116e-01, 2.5732e-01, 9.6763e-02, 5.6920e-01],
         [4.2386e-01, 8.0103e-01, 4.8222e-01, 8.9719e-01, 8.9955e-02,
          6.1831e-01, 3.5209e-01, 8.1020e-01, 1.9322e-01, 5.3762e-01],
         [7.7699e-01, 1.4197e-02, 4.2572e-01, 4.6923e-01, 1.7798e-02,
          1.4418e-01, 1.0582e-01, 9.8089e-01, 4.2284e-01, 1.1514e-01],
         [7.8408e-02, 4.1396e-01, 1.4917e-01, 9.0548e-02, 1.8227e-01,
          7.6952e-01, 5.3100e-01, 9.8282e-01, 8.7117e-02, 2.5278e-02],
         [5.4662e-01, 5.7157e-01, 5.5958e-01, 8.6485e-01, 8.1306e-01,
          3.8392e-01, 3.9169e-02, 2.3008e-01, 3.1520e-01, 4.2547e-01],
         [2.2

In [23]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9779, 0.0136, 0.6886, 0.3304],
        [0.1943, 0.4580, 0.3546, 0.8689],
        [0.2554, 0.6508, 0.0894, 0.7376]])

In [24]:
random_tensor.ndim

2

In [25]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channel #RGB
random_image_size_tensor.ndim

3

In [26]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and ones

In [28]:
zeros = torch.zeros(3,4)

In [29]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
ones = torch.ones(3,4)

In [32]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [35]:
one_to_ten = torch.arange(1,11)  #start,end,step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])