## 00. PyTorch Fundamentals FreeCodeCamp mrdbrouke

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


#Introduction to Tensors

##Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim  #scalar has no dimensions

0

In [ ]:
scalar.item()  #tensor back as python int

7

In [ ]:
#vector
vector = torch.tensor((1,7))
vector

tensor([1, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
  #Matrix

  MATRIX = torch.tensor([[7,8],
                         [9,10]])
  MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape   #we have 1 -3*3 matrix

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

They are important as many NNs learn is that when they start, it is with random numbers and then adjust the numbers to a better representation of numbers



start with random numbers -> look at data -> update random numbers -> look at data -> update

In [ ]:
random_tensor = torch.rand(10,10,10)
random_tensor

tensor([[[6.3125e-01, 6.3973e-01, 6.5687e-01, 2.0218e-01, 9.1766e-01,
          6.5235e-01, 2.2808e-02, 1.6575e-01, 6.6542e-02, 3.2724e-01],
         [6.2387e-01, 5.1152e-01, 9.1302e-01, 5.3470e-01, 3.6705e-01,
          6.2966e-01, 4.3801e-01, 7.3392e-01, 2.8484e-01, 2.2610e-01],
         [5.3206e-01, 2.0454e-02, 8.2877e-01, 4.8589e-01, 2.1121e-01,
          6.5266e-01, 7.6399e-01, 7.4409e-01, 9.7728e-01, 3.6944e-02],
         [6.7572e-01, 4.6500e-01, 9.2131e-01, 4.5818e-02, 7.1571e-01,
          3.4773e-01, 8.7249e-01, 1.2284e-01, 4.8983e-01, 5.2429e-01],
         [5.6881e-01, 5.7972e-01, 8.5306e-02, 4.9436e-02, 5.5888e-01,
          9.2245e-01, 2.4754e-01, 5.8029e-01, 6.7433e-01, 3.7447e-01],
         [3.8131e-01, 3.7562e-01, 8.3159e-01, 1.6411e-01, 5.2859e-01,
          5.4191e-01, 7.2867e-01, 7.6577e-01, 3.8172e-01, 7.8167e-01],
         [1.5543e-01, 7.2054e-01, 3.4048e-01, 7.6670e-02, 4.4102e-01,
          3.5751e-01, 3.1177e-02, 3.2519e-01, 1.8711e-02, 3.2950e-01],
         [2.4

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2532, 0.0127, 0.4366, 0.4028],
        [0.5788, 0.5941, 0.0324, 0.3726],
        [0.6810, 0.2235, 0.6318, 0.6710]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channel #RGB
random_image_size_tensor.ndim

3

In [ ]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and ones

In [ ]:
zeros = torch.zeros(3,4)

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(1,11)  #start,end,step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, #default remains float32
                               device = None, #what device your tensor is on
                               requires_grad = False) # whether or not to track gradients

In [ ]:
float_32_tensor.dtype

torch.float32

**NOTE**  datatype is one of the most came across errors in tensors

[other 2 are shape and device]

32 bit tensor is full precision

16 bit is half precision

64 bit is more precision

it represents how much detail one cna hold it

In [ ]:
#converting float 32 tensor to float 16 tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
(int_32_tensor * float_32_tensor).dtype

torch.float32

## getting information from tensors - attributes

tensors not right type - tensor.dtype to check

not right shape - tensor.shape

not the right device - tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9923, 0.5180, 0.7686, 0.4960],
        [0.6767, 0.0811, 0.0402, 0.5292],
        [0.9716, 0.3867, 0.1174, 0.1464]])

In [ ]:
## find details about the tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device our tensor is on:{some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device our tensor is on:cpu


###Manipulating tensors (tensor operations)

Tensor operations include:
* addition
* subtraction
* multiplication (element-wise)
* division
* matrix multiplication

In [ ]:
# Create a tensor
tensor1 = torch.tensor([1,2,3,])
tensor1+10

tensor([11, 12, 13])

In [ ]:
#multiply
tensor1*10

tensor([10, 20, 30])

In [ ]:
tensor1- 10

tensor([-9, -8, -7])

In [ ]:
tensor1/12

tensor([0.0833, 0.1667, 0.2500])

In [ ]:
## trying out PyTorch in-built function
## generally used for specific reasons, usually we work with operators
torch.mul(tensor1,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor1,2)

tensor([3, 4, 5])

## two ways of preforming multiplication in neural networks and deep learning:

1. element-wise
2. dot product or the matrix multiplication


In [ ]:
#elementwise
print(tensor1, '*', tensor1)
print(f"Equals: {tensor1*tensor1}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor1,tensor1)

tensor(14)

In [ ]:
tensor1 @ tensor1

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor1)):
  value += tensor1[i] * tensor1[i]
print(value)

tensor(14)
CPU times: user 1.96 ms, sys: 0 ns, total: 1.96 ms
Wall time: 2.18 ms


In [ ]:
%%time
torch.matmul(tensor1,tensor1)

CPU times: user 1.32 ms, sys: 0 ns, total: 1.32 ms
Wall time: 2.45 ms


tensor(14)

### One of the most common errors in DL: shape error

In [ ]:
# Shapes for matrix multiplication

tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,8],
                         [8,11],
                         [9,12]])

#torch.mm is an alias for torch.matmul
torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our shape issues, we can manipulate the tensor by transposing it

In [ ]:
tensor_b.T

tensor([[ 7,  8,  9],
        [ 8, 11, 12]])

In [ ]:
tensor_b.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_a,tensor_b.T)

tensor([[ 23,  30,  33],
        [ 53,  68,  75],
        [ 83, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)


In [ ]:
x = torch.arange(1,100,10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

#reshaping, stacking, squeezing and unsqueezing tensors

* reshaping - reshape an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) orside by side (hstack)
* squeeze - removes all '1' dimensions from tensors
* unsqueeze - add a '1' dimension to a target tensor
* permute - return a view of the input with the dimensions permuted (swapped) in a certain way

In [ ]:
#lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped ,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x2 = torch.arange(1.,13.)
x2_reshaped = x2.reshape(3,4)
x2_reshaped

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
#change the view

#changing z changes x, as they share the same memory

z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)

In [ ]:
x_stacked.ndim

2

In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

stacked_tensor_dim0 = torch.stack([tensor1, tensor2], dim=0)  # Stack along first dimension
# stacked_tensor_dim0: tensor([[1, 2, 3],
#                             [4, 5, 6]])

stacked_tensor_dim1 = torch.stack([tensor1, tensor2], dim=1)  # Stack along second dimension
# stacked_tensor_dim1: tensor([[1, 4],
#                             [2, 5],
#                             [3, 6]])

In [ ]:
##squeeze()

x_reshaped, x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_reshaped.unsqueeze(dim=0)

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [ ]:
x_reshaped.unsqueeze(dim=0).shape

torch.Size([1, 9, 1])

In [ ]:
x_reshaped.unsqueeze(dim=1),x_reshaped.unsqueeze(dim=1).shape

(tensor([[[5.]],
 
         [[2.]],
 
         [[3.]],
 
         [[4.]],
 
         [[5.]],
 
         [[6.]],
 
         [[7.]],
 
         [[8.]],
 
         [[9.]]]),
 torch.Size([9, 1, 1]))

In [2]:
##permute

x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)  #shifts axis 0to1, 1to2, 2to0

In [3]:
x_permuted.shape

torch.Size([3, 224, 224])

In [4]:
x_original[0,0,0] = 0.18362

In [5]:
x_original[0,0,0], x_permuted[0,0,0]

(tensor(0.1836), tensor(0.1836))

###INdexing (selecting data from tensros)
Indexing with PyTorch similar to indexing with NumPy

In [6]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
x[0][0]

tensor([1, 2, 3])

In [10]:
x[0][0][0]

tensor(1)

In [12]:
x[0][1][1]

tensor(5)

In [13]:
x[:,0]

tensor([[1, 2, 3]])

In [14]:
x[:,:,1]  #get all values of 0th and 1st dimension and 1 index value of second dimension

tensor([[2, 5, 8]])

In [16]:
x[:,1,1], x[0,1,1]

(tensor([5]), tensor(5))

In [18]:
x[0,0,:]

tensor([1, 2, 3])

In [19]:
x[:,:,2]

tensor([[3, 6, 9]])

##PyTorch and Numpy

* data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> `torch.Tensor.numpy()`

In [20]:
import numpy as np

In [21]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [22]:
array.dtype

dtype('float64')

In [23]:
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [24]:
#Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility (trying to take random out of random)

In short how a NN leanrs:

`start with random numbers -> tensor operations -> update random numbers to try and make them better respresentation of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of *Random seed*
It flavours the randomness

In [25]:
a = torch.rand(3,4)
b = torch.rand(3,4)

a==b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [26]:
##making random but reproducible tensors

Random_seed = 42
torch.manual_seed(Random_seed)
random_c = torch.rand(3,4)

torch.manual_seed(Random_seed)
random_d = torch.rand(3,4)

print(random_d)
print(random_c)
print(random_c==random_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


GPUs = faster computation on numbers

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = 'cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
torch.cuda.device_count()

1

##Putting tensors (and models) on the GPU
 for faster computations

In [4]:
# Create a tensor
tensor1 = torch.tensor([1,2,3], device='cpu')

print(tensor1, tensor1.device)

tensor([1, 2, 3]) cpu


In [5]:
##Move tensor to GPU (if available)
tensor_on_gpu = tensor1.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Moving tenosrs back to a CPU

In [6]:
##If the tensor is on GPU, it does not work with NumPy

tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [7]:
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])